prefix skos:    <http://www.w3.org/2004/02/skos/core#>

select  count( *) where {

		?concept skos:prefLabel ?prefLabels.
	OPTONAL{
		?concept skos:altLabel ?altLabels.
	}
	FILTER (?preskos:altLabel ?altLabels.}
	
}
	




